"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ModredIP__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ModredIP__factory_1 = require("./ModredIP__factory");
Object.defineProperty(exports, "ModredIP__factory", { enumerable: true, get: function () { return ModredIP__factory_1.ModredIP__factory; } });
