/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ModredIP } from "./ModredIP";
export * as factories from "./factories";
export { ModredIP__factory } from "./factories/ModredIP__factory";
